version: "3.8"

services:

  db:
    container_name: ${MYSQL_DATABASE_CONTAINER_NAME}
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TIMEZONE: $TIMEZONE}
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - ${MYSQL_PORT:-3306}:3306
    expose:
      # Opens port 3306 on the container
      - ${MYSQL_PORT:-3306}
    volumes:
      - ./mysql:/var/lib/mysql

  app:
    container_name: app
    build:
      context: ./.docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  nginx:
    container_name: ${NGINX_PROXY_CONTAINER_NAME}
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - ${NGINX_PROXY_PORT_HOST}:80
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - VIRTUAL_PROTO:https
      - HTTPS_METHOD:https
      - VIRTUAL_PORT:443
    depends_on:
      - app
      - db
